//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDBMS.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public Accounts()
        {
            this.Employees = new HashSet<Employees>();
            this.Guests = new HashSet<Guests>();
            this.Reservations = new HashSet<Reservations>();
            this.Rooms = new HashSet<Rooms>();
        }
    
        public int id { get; set; }
        public string acctname { get; set; }
        public string acctpass { get; set; }
        public string acctstatus { get; set; }
        public Nullable<int> creatorID { get; set; }
        public Nullable<int> roleID { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual ICollection<Guests> Guests { get; set; }
        public virtual ICollection<Reservations> Reservations { get; set; }
        public virtual ICollection<Rooms> Rooms { get; set; }
    }
}
