//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDBMS.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int id { get; set; }
        public string stafffn { get; set; }
        public string staffln { get; set; }
        public System.DateTime staffbdate { get; set; }
        public string staffgender { get; set; }
        public string staffcontact { get; set; }
        public string staffemail { get; set; }
        public Nullable<decimal> staffsalary { get; set; }
        public Nullable<int> acctID { get; set; }
        public Nullable<int> roleID { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
