//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDBMS.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guests
    {
        public Guests()
        {
            this.Reservations = new HashSet<Reservations>();
        }
    
        public int id { get; set; }
        public string guestfn { get; set; }
        public string guestln { get; set; }
        public System.DateTime guestbdate { get; set; }
        public string guestgender { get; set; }
        public bool guestHasReservation { get; set; }
        public Nullable<int> acctID { get; set; }
        public Nullable<int> roomID { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Rooms Rooms { get; set; }
        public virtual ICollection<Reservations> Reservations { get; set; }
    }
}
