//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDBMS.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class HotelDBEntities : DbContext
    {
        public HotelDBEntities()
            : base("name=HotelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Accounts> Accounts { get; set; }
        public DbSet<Employees> Employees { get; set; }
        public DbSet<Guests> Guests { get; set; }
        public DbSet<Reservations> Reservations { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Rooms> Rooms { get; set; }
        public DbSet<ViewGuest_Default> ViewGuest_Default { get; set; }
        public DbSet<ViewReservations_Default> ViewReservations_Default { get; set; }
        public DbSet<ViewRooms_Default> ViewRooms_Default { get; set; }
    
        public virtual int SP_Guest_Delete(Nullable<int> gid)
        {
            var gidParameter = gid.HasValue ?
                new ObjectParameter("gid", gid) :
                new ObjectParameter("gid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Guest_Delete", gidParameter);
        }
    
        public virtual int SP_Guest_Update(Nullable<int> gid, string fn, string ln, string gender, Nullable<System.DateTime> bdate)
        {
            var gidParameter = gid.HasValue ?
                new ObjectParameter("gid", gid) :
                new ObjectParameter("gid", typeof(int));
    
            var fnParameter = fn != null ?
                new ObjectParameter("fn", fn) :
                new ObjectParameter("fn", typeof(string));
    
            var lnParameter = ln != null ?
                new ObjectParameter("ln", ln) :
                new ObjectParameter("ln", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var bdateParameter = bdate.HasValue ?
                new ObjectParameter("bdate", bdate) :
                new ObjectParameter("bdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Guest_Update", gidParameter, fnParameter, lnParameter, genderParameter, bdateParameter);
        }
    
        public virtual int SP_Guest_Update_Booking(Nullable<int> gid, string fn, string ln, string gender, Nullable<System.DateTime> bdate, Nullable<int> rid)
        {
            var gidParameter = gid.HasValue ?
                new ObjectParameter("gid", gid) :
                new ObjectParameter("gid", typeof(int));
    
            var fnParameter = fn != null ?
                new ObjectParameter("fn", fn) :
                new ObjectParameter("fn", typeof(string));
    
            var lnParameter = ln != null ?
                new ObjectParameter("ln", ln) :
                new ObjectParameter("ln", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var bdateParameter = bdate.HasValue ?
                new ObjectParameter("bdate", bdate) :
                new ObjectParameter("bdate", typeof(System.DateTime));
    
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Guest_Update_Booking", gidParameter, fnParameter, lnParameter, genderParameter, bdateParameter, ridParameter);
        }
    
        public virtual int SP_Reservation_Update_CheckIn(Nullable<int> rid, Nullable<System.DateTime> checkindate)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var checkindateParameter = checkindate.HasValue ?
                new ObjectParameter("checkindate", checkindate) :
                new ObjectParameter("checkindate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Reservation_Update_CheckIn", ridParameter, checkindateParameter);
        }
    
        public virtual int SP_Reservation_Update_CheckOut(Nullable<int> rid, Nullable<System.DateTime> checkoutdate)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var checkoutdateParameter = checkoutdate.HasValue ?
                new ObjectParameter("checkoutdate", checkoutdate) :
                new ObjectParameter("checkoutdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Reservation_Update_CheckOut", ridParameter, checkoutdateParameter);
        }
    
        public virtual int SP_Room_Delete(Nullable<int> rid)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Room_Delete", ridParameter);
        }
    
        public virtual int SP_Room_Update(Nullable<int> rid, string rname, string rtype, Nullable<decimal> rprice, string rdesc)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var rnameParameter = rname != null ?
                new ObjectParameter("rname", rname) :
                new ObjectParameter("rname", typeof(string));
    
            var rtypeParameter = rtype != null ?
                new ObjectParameter("rtype", rtype) :
                new ObjectParameter("rtype", typeof(string));
    
            var rpriceParameter = rprice.HasValue ?
                new ObjectParameter("rprice", rprice) :
                new ObjectParameter("rprice", typeof(decimal));
    
            var rdescParameter = rdesc != null ?
                new ObjectParameter("rdesc", rdesc) :
                new ObjectParameter("rdesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Room_Update", ridParameter, rnameParameter, rtypeParameter, rpriceParameter, rdescParameter);
        }
    
        public virtual int SP_Room_Update_Avail(Nullable<int> rid)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Room_Update_Avail", ridParameter);
        }
    
        public virtual int SP_Room_Update_Occupy(Nullable<int> rid, Nullable<int> count, Nullable<int> aid)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var countParameter = count.HasValue ?
                new ObjectParameter("count", count) :
                new ObjectParameter("count", typeof(int));
    
            var aidParameter = aid.HasValue ?
                new ObjectParameter("aid", aid) :
                new ObjectParameter("aid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Room_Update_Occupy", ridParameter, countParameter, aidParameter);
        }
    
        public virtual int SP_Reservation_Create(Nullable<System.DateTime> indate, Nullable<System.DateTime> outdate, Nullable<int> adults, Nullable<int> children, Nullable<int> aid, Nullable<int> rid, Nullable<int> gid)
        {
            var indateParameter = indate.HasValue ?
                new ObjectParameter("indate", indate) :
                new ObjectParameter("indate", typeof(System.DateTime));
    
            var outdateParameter = outdate.HasValue ?
                new ObjectParameter("outdate", outdate) :
                new ObjectParameter("outdate", typeof(System.DateTime));
    
            var adultsParameter = adults.HasValue ?
                new ObjectParameter("adults", adults) :
                new ObjectParameter("adults", typeof(int));
    
            var childrenParameter = children.HasValue ?
                new ObjectParameter("children", children) :
                new ObjectParameter("children", typeof(int));
    
            var aidParameter = aid.HasValue ?
                new ObjectParameter("aid", aid) :
                new ObjectParameter("aid", typeof(int));
    
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var gidParameter = gid.HasValue ?
                new ObjectParameter("gid", gid) :
                new ObjectParameter("gid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Reservation_Create", indateParameter, outdateParameter, adultsParameter, childrenParameter, aidParameter, ridParameter, gidParameter);
        }
    
        public virtual int SP_Account_Create_Register(string name, string pass, Nullable<int> roleid, Nullable<int> creatorid)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var roleidParameter = roleid.HasValue ?
                new ObjectParameter("roleid", roleid) :
                new ObjectParameter("roleid", typeof(int));
    
            var creatoridParameter = creatorid.HasValue ?
                new ObjectParameter("creatorid", creatorid) :
                new ObjectParameter("creatorid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Account_Create_Register", nameParameter, passParameter, roleidParameter, creatoridParameter);
        }
    
        public virtual int SP_Guest_Create_Register(string fn, string ln, Nullable<System.DateTime> bdate, string gender, Nullable<int> aid)
        {
            var fnParameter = fn != null ?
                new ObjectParameter("fn", fn) :
                new ObjectParameter("fn", typeof(string));
    
            var lnParameter = ln != null ?
                new ObjectParameter("ln", ln) :
                new ObjectParameter("ln", typeof(string));
    
            var bdateParameter = bdate.HasValue ?
                new ObjectParameter("bdate", bdate) :
                new ObjectParameter("bdate", typeof(System.DateTime));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var aidParameter = aid.HasValue ?
                new ObjectParameter("aid", aid) :
                new ObjectParameter("aid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Guest_Create_Register", fnParameter, lnParameter, bdateParameter, genderParameter, aidParameter);
        }
    }
}
