//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDBMS.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int id { get; set; }
        public System.DateTime resScheduleCheckin { get; set; }
        public System.DateTime resScheduleCheckout { get; set; }
        public int resAdults { get; set; }
        public int resChildren { get; set; }
        public Nullable<System.DateTime> resCheckinDate { get; set; }
        public Nullable<System.DateTime> resCheckoutDate { get; set; }
        public Nullable<int> acctID { get; set; }
        public Nullable<int> roomID { get; set; }
        public Nullable<int> guestID { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Guests Guests { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
