//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDBMS.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewRooms_Default
    {
        public string roomname { get; set; }
        public string roomtype { get; set; }
        public decimal roomprice { get; set; }
        public int roomoccupants { get; set; }
        public string acctname { get; set; }
        public string roomdesc { get; set; }
    }
}
