//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDBMS.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewGuest_Default
    {
        public string Full_Name { get; set; }
        public string Gender { get; set; }
        public string Birth_Date { get; set; }
        public string Account_Username { get; set; }
    }
}
