//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDBMS.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewReservations_Default
    {
        public string roomname { get; set; }
        public decimal roomprice { get; set; }
        public System.DateTime resScheduleCheckin { get; set; }
        public System.DateTime resScheduleCheckout { get; set; }
        public Nullable<System.DateTime> resCheckinDate { get; set; }
        public Nullable<System.DateTime> resCheckoutDate { get; set; }
        public int resAdults { get; set; }
        public int resChildren { get; set; }
        public string Occupant_Full_Name { get; set; }
    }
}
